#!/bin/sh
#
# Adds the PPA for the newest toolchain to the pbuilder environment.
#
# Only enable this when prepping releases for newer toolchains.
#
#apt-get install --yes software-properties-common
#apt-add-repository --yes ppa:ubuntu-toolchain-r/test 
echo "I: Use newest toolchain from ppa:ubuntu-toolchain-r/test"
echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu $DISTRIBUTION main" >>/etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-key 60C317803A41BA51845E371A1E9377A2BA9EF27F
